### ISSUE TITLE
Fatal Errors

### ISSUE THREAD

**Issue by josh6025** [rudiedirkx/Fuelly#1]
When trying to load the test files I'm getting some fatal errors which I'm unable to resolve.

![fapi1](https://user-images.githubusercontent.com/831011/33244386-223811dc-d2c4-11e7-8bb4-7c70087bcd5f.PNG)

![fapi2](https://user-images.githubusercontent.com/831011/33244388-23ac8048-d2c4-11e7-89a3-4e8593698111.PNG)

**Comment by rudiedirkx** [comment]
I don't see a fatal error. I see a bunch of HTML. Wanna clean that up? You can turn off xdebug of turn off html errors, or copy the output, not the source. I'm not attempting to read that.

**Comment by rudiedirkx** [comment]
Also, which test file?
